### ISSUE TITLE
Замечания lw1

### ISSUE THREAD

**Issue by ivklgn** [ShulepovDen/first-lab#1]
- пройтись prettier'ом по css коду
- имена папок должны писаться однотипно (с маленькой буквы)
- indexDark.html -> index-dark.html
- media -> images
- style -> css
- NORDIC ROSE dark -> Nordic-rose-dark

**Comment by ivklgn** [comment]
верстка съехала, проверить по макету

**Comment by ivklgn** [comment]
для пунктов меню и ссылок используйте курсор (css атрибут cursor)

**Comment by ivklgn** [comment]
```css
.header-left img {
  width: 395.83px;
  height: 37.53px;
  margin: 52.54px 0 0 63.58px;
}
```

для картинки создать класс
